"""Add year_in_which_joined column to Dues model

Revision ID: a97db323f1a4
Revises: 
Create Date: 2024-05-08 17:15:58.832086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97db323f1a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_in_which_joined', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('year_in_which_course_completed', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mobile_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('library_image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hostel_image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hod_image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('placement_office_image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_suptd_image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('academic_suptd_image', sa.String(length=100), nullable=True))
        batch_op.drop_column('placement_office')
        batch_op.drop_column('academic_supdt')
        batch_op.drop_column('hostel')
        batch_op.drop_column('library')
        batch_op.drop_column('yearinwhichjoined')
        batch_op.drop_column('hod')
        batch_op.drop_column('account_supdt')
        batch_op.drop_column('mobile_no')
        batch_op.drop_column('yearinwhichcourseiscompleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yearinwhichcourseiscompleted', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('mobile_no', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('account_supdt', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('hod', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('yearinwhichjoined', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('library', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('hostel', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('academic_supdt', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('placement_office', sa.TEXT(), nullable=False))
        batch_op.drop_column('academic_suptd_image')
        batch_op.drop_column('account_suptd_image')
        batch_op.drop_column('placement_office_image')
        batch_op.drop_column('hod_image')
        batch_op.drop_column('hostel_image')
        batch_op.drop_column('library_image')
        batch_op.drop_column('mobile_number')
        batch_op.drop_column('year_in_which_course_completed')
        batch_op.drop_column('year_in_which_joined')

    # ### end Alembic commands ###
